/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tools */
        get: operations["tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demand */
        post: operations["create_demand_api_v1_demand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/similar-precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Similar Precheck
         * @description 相似需求预检。
         *
         *     实盘核对结论：本机网关实例**未暴露** `demand_similar_precheck` 工具
         *     （源码 gateway/app.py 有定义，但容器跑的是旧镜像；tools/list 只有 41 个）。
         *     因此这里优先调原生工具，不可用时降级为「demand_list 拉候选 + difflib
         *     字符级相似度」，语义与 gateway/demand.py:163 find_similar 保持一致。
         */
        post: operations["similar_precheck_api_v1_demand_similar_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_demand__demand_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/e2e-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * E2E Status
         * @description 一次打包 6 个 MCP 工具结果，前端只调1 次。
         *
         *     硬要求：任一子调用失败**不得整体 500**。失败项写入 partial_errors，
         *     并标明缺的是哪一块，前端据此灰掉对应区块而不是整页报错。
         */
        get: operations["e2e_status_api_v1_demand__demand_id__e2e_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description 答复一条口径确认。
         *
         *     实盘行为：答复本身**不会**回填槽位、也不会作为 P2 证据进入证据链。
         *     必须在答复后重跑一次 analyze。所以这里内部串行做「答复 → 重跑分析」，
         *     并把两段结果一起返回，前端可直接对比槽位是否已被回填。
         */
        post: operations["confirm_api_v1_demand__demand_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sql Generate */
        post: operations["sql_generate_api_v1_demand__demand_id__sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/sql/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sql Execute */
        post: operations["sql_execute_api_v1_demand__demand_id__sql_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/{demand_id}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Citations
         * @description 知识引用明细。
         *
         *     实盘核对结论：本机网关实例**未暴露** `knowledge_citation_list`。
         *     这里优先调原生工具；不可用时降级用 `knowledge_search` 取该需求的引用线索，
         *     并在 source 字段标明降级，避免前端误以为是权威留痕表。
         */
        get: operations["citations_api_v1_demand__demand_id__citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeIn */
        AnalyzeIn: {
            /**
             * Dataset
             * @description 数据集（A/B）
             * @default B
             */
            dataset: string;
            /**
             * Actor
             * @description 操作人
             * @default
             */
            actor: string;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
            /** Choice */
            choice?: string | null;
            /**
             * Actor
             * @default
             */
            actor: string;
        };
        /** DemandCreateIn */
        DemandCreateIn: {
            /**
             * Title
             * @description 需求标题
             */
            title: string;
            /**
             * Business Context
             * @description 业务背景
             */
            business_context: string;
            /**
             * Description
             * @description 需求说明
             */
            description: string;
            /**
             * Expected Output
             * @description 输出预期
             */
            expected_output: string;
            /**
             * Contact
             * @description 联系人
             */
            contact: string;
            /**
             * Time Range
             * @description 时间范围
             */
            time_range?: string | null;
            /**
             * Expected Finish At
             * @description 期望完成时间
             */
            expected_finish_at?: string | null;
            /**
             * Actor
             * @description 提交人
             * @default
             */
            actor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SimilarPrecheckIn */
        SimilarPrecheckIn: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Top
             * @default 5
             */
            top: number;
            /**
             * Threshold
             * @default 0.55
             */
            threshold: number;
        };
        /** SqlExecuteIn */
        SqlExecuteIn: {
            /**
             * Dataset
             * @default B
             */
            dataset: string;
            /** Sql */
            sql?: string | null;
            /**
             * Actor
             * @default
             */
            actor: string;
        };
        /** SqlIn */
        SqlIn: {
            /**
             * Dataset
             * @default B
             */
            dataset: string;
            /** Candidate Sql */
            candidate_sql?: string | string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_demand_api_v1_demand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_precheck_api_v1_demand_similar_precheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarPrecheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_demand__demand_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    e2e_status_api_v1_demand__demand_id__e2e_status_get: {
        parameters: {
            query?: {
                dataset?: string;
                run_limit?: number;
            };
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_demand__demand_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sql_generate_api_v1_demand__demand_id__sql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sql_execute_api_v1_demand__demand_id__sql_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlExecuteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    citations_api_v1_demand__demand_id__citations_get: {
        parameters: {
            query?: {
                include_retired?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                demand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
